x-airflow-common: &airflow-common
  image: apache/airflow:2.8.1-python3.10
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
    AIRFLOW__SMTP__SMTP_HOST: 'smtp.yandex.ru'
    AIRFLOW__SMTP__SMTP_PORT: 465
    AIRFLOW__SMTP__SMTP_STARTTLS: 'False'
    AIRFLOW__SMTP__SMTP_SSL: 'True'
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    AIRFLOW__SMTP__SMTP_USER: ${YANDEX_SMTP_USER}
    AIRFLOW__SMTP__SMTP_PASSWORD: ${YANDEX_SMTP_PASSWORD}
    AIRFLOW__SMTP__SMTP_MAIL_FROM: ${YANDEX_SMTP_USER}
    
    CH_USER: ${CLICKHOUSE_USER}
    CH_PASSWORD: ${CLICKHOUSE_PASSWORD}  

    LANG: en_US.UTF-8

    SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./for_load:/opt/airflow/data
    - .:/opt/airflow/dbt_project
    - ${AIRFLOW_PROJ_DIR:-.}/requirements-local.txt:/requirements.txt
  networks:
    - data_network

services:
  # --- ХРАНИЛИЩЕ ДАННЫХ ---
  clickhouse-course1:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      TZ: UTC
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - data_network

  # --- ТРАНСФОРМАЦИЯ ДАННЫХ (ЛОКАЛЬНЫЙ РАННЕР) ---
  dbt:
    build:
      context: . 
    container_name: dbt_runner
    environment:
      - DBT_PROFILES_DIR=/usr/app
    volumes:
      - .:/usr/app
    networks:
      - data_network
    depends_on:
      - clickhouse-course1

  # --- БАЗА ДАННЫХ ДЛЯ МЕТАДАННЫХ (AIRFLOW) ---
  postgres:
    image: postgres:15-alpine
    container_name: platform_metadata_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - data_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U platform_admin -d airflow_metadata"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- ОРКЕСТРАТОР AIRFLOW ---
  airflow-init:
    <<: *airflow-common
    container_name: airflow_init
    entrypoint: /bin/bash
    command: -c "airflow db init && airflow users create --username $${AIRFLOW_ADMIN_USER} --firstname Admin --lastname Admin --role Admin --email admin@example.com --password $${AIRFLOW_ADMIN_PASSWORD}"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - data_network

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    # Возвращаем стандартную быструю команду Airflow
    command: webserver
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    # Добавляем стандартную сеть bridge для доступа в интернет
    networks:
      - data_network
      - default

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    # Возвращаем стандартную быструю команду Airflow
    command: scheduler
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    # Добавляем стандартную сеть bridge для доступа в интернет
    networks:
      - data_network
      - default

  # --- БИЗНЕС-АНАЛИТИКА SUPERSET ---
  superset:
    image: apache/superset:3.1.0
    container_name: superset_bi
    user: root  
    entrypoint: [ "/bin/sh", "-c", "pip install clickhouse-connect && /usr/bin/run-server.sh" ]
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
    networks:
      - data_network

  # --- ОБЪЕКТНОЕ ХРАНИЛИЩЕ MINIO (АНАЛОГ AWS S3) ---
  minio:
    image: minio/minio:latest
    container_name: minio_storage
    ports:
      - "9005:9000"  
      - "9001:9001"  
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - data_network

# --- ТОМА И СЕТИ ---
volumes:
  clickhouse_data:
    external: true 
  postgres_data: 
  minio_data:    

networks:
  data_network:
    external: true
    name: clickhouse_data_network